import string
from CONSTANTS import *

class Projectile(pygame.sprite.Sprite):
    """ This class represents the projectiles. Currently these can only
    be used by Commet. Will be updated in the future """
    def __init__(self, x_pos: int, y_pos: int, direction: int, proj_type: string):
        pygame.sprite.Sprite.__init__(self)
        self.speed = 10 # Speed should change depending on projectile type
        self.type = proj_type
        self.image = PROJ_IMG[proj_type] # ensure the correct image is loaded
        self.rect = self.image.get_rect() # Need the rect generated by the image to detect collisions
        self.rect.center = (x_pos, y_pos)
        self.direction = direction
        if self.direction == -1:
            self.image = pygame.transform.flip(self.image, True, False) # ensure that the image is facing the right way (True argument indicates horizontal axis flip)

    def update(self):
        self.rect.x += (self.direction) * (self.speed)

        if self.rect.right < 0 or self.rect.left > SCREEN_WIDTH:
            self.kill()


projectile_group = pygame.sprite.Group() # this is a built in pygame feature to handle drawing and updates of all instances of this group on our behalf